#!/usr/bin/env python3
"""Deterministic Markdown projections of authoritative engagement records."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from engagement_records import RecordError
from engagement_state import atomic_write

SENTINEL = "<!-- GENERATED by tools/run-engagement.py; edit authoritative records, not this file. -->"


def _bullets(values: list[str], empty: str = "None.") -> str:
    return "\n".join(f"- `{value}`" for value in values) if values else empty


def render_views(snapshot: dict[str, Any]) -> dict[str, bytes]:
    engagement_id = snapshot["engagement_id"]
    candidate_lines = [f"- `{key}` — {value.get('status', 'unknown')}" for key, value in sorted(snapshot["candidates"].items())]
    hypothesis_lines = [f"- `{key}` — {value.get('status', 'unknown')}" for key, value in sorted(snapshot["hypotheses"].items())]
    finding_lines = [f"- `{key}` rev {value.get('revision')} — {value.get('status') or 'ungraded'}" for key, value in sorted(snapshot["findings"].items())]
    progress = f"""{SENTINEL}
# Progress — {engagement_id}

- Scope: attested `{snapshot['scope_hash']}`
- Environment: `{snapshot['active_environment_ref'] or 'not-recorded'}`
- Coverage: `{snapshot['coverage']}`
- Events: {snapshot['event_count']}
- Attempts: {snapshot['attempt_count']}
- Artifacts: {snapshot['artifact_count']}
- Last event: `{snapshot['last_event_id']}`

## Active blockers

{_bullets(snapshot['active_blockers'])}

## Candidates

{chr(10).join(candidate_lines) if candidate_lines else 'None.'}

## Likely-held / control candidates

{_bullets([item['routing_event_id'] for item in snapshot['control_candidates']])}

## Hypotheses

{chr(10).join(hypothesis_lines) if hypothesis_lines else 'None.'}

## Findings

{chr(10).join(finding_lines) if finding_lines else 'None.'}
"""
    reviews = f"""{SENTINEL}
# Review index — {engagement_id}

Outstanding review obligations: {len(snapshot['outstanding_reviews'])}.

{_bullets([str(item.get('review_type', 'unknown')) for item in snapshot['outstanding_reviews']])}
"""
    reports = f"""{SENTINEL}
# Report index — {engagement_id}

{_bullets(snapshot['report_refs'], 'No generated reports.')}
"""
    submissions = f"""{SENTINEL}
# Submission index — {engagement_id}

{_bullets(snapshot['submission_refs'], 'No operator-owned submission records.')}
"""
    memory_state = snapshot["memory_disposition"]
    memory_status = memory_state["disposition"] if memory_state else "pending"
    memory_ref = memory_state["disposition_ref"] if memory_state else "none"
    memory = f"""{SENTINEL}
# Memory disposition — {engagement_id}

Disposition: `{memory_status}`. Record: `{memory_ref}`.

This view does not promote Plane-1 memory. Promotion remains an operator-reviewed change.
"""
    cleanup_items = [f"{item['obligation_id']}: {item['status']}" for item in snapshot["cleanup"]["obligations"]]
    cleanup = f"""{SENTINEL}
# Mechanical cleanup status — {engagement_id}

Disposition recorded: `{str(snapshot['cleanup']['recorded']).lower()}`.

{_bullets(cleanup_items, 'No structured cleanup obligations recorded.')}

`cleanup.md` remains the human ledger and is not overwritten by this projection.
"""
    return {
        "progress.md": progress.encode("utf-8"),
        "reviews/README.md": reviews.encode("utf-8"),
        "views/report-index.md": reports.encode("utf-8"),
        "views/submission-index.md": submissions.encode("utf-8"),
        "memory/README.md": memory.encode("utf-8"),
        "cleanup.generated.md": cleanup.encode("utf-8"),
    }


def write_views(engagement: Path, snapshot: dict[str, Any]) -> None:
    for relative, data in render_views(snapshot).items():
        atomic_write(engagement / relative, data)


def check_views(engagement: Path, snapshot: dict[str, Any]) -> list[str]:
    stale = []
    for relative, expected in render_views(snapshot).items():
        path = engagement / relative
        if not path.is_file() or path.read_bytes() != expected:
            stale.append(relative)
    return stale


def assert_views_current(engagement: Path, snapshot: dict[str, Any]) -> None:
    stale = check_views(engagement, snapshot)
    if stale:
        raise RecordError("stale_derived_views", ", ".join(stale))
